
 spring:
   data:
     elasticsearch:
       properties:
         node.name: fii-client
         node.master: false
         node.data: false
       #cluster-nodes: 192.168.56.53:9300
       cluster-nodes: 127.0.0.1:9300
 logging:
   level:
     ROOT: INFO
     org.elasticsearch.bootstrap: ERROR
     fii.practic: DEBUG
 server:
   port: 9720