
 spring:
   data:
     elasticsearch:
       properties:
         #discovery.zen.ping.unicast.hosts: ["127.0.0.1", "[::1]", "192.168.56.1"]
         node.name: fii-client
         node.master: false
         node.data: false
       #cluster-nodes: 192.168.56.53:9300
 logging:
   level:
     ROOT: INFO
     org.elasticsearch.bootstrap: ERROR
     fii.practic: DEBUG
server:
   port: 9720